//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Experience {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Experience() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portfolio.Resources.Pages.Experience", typeof(Experience).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Job.
        /// </summary>
        public static string activitiesType {
            get {
                return ResourceManager.GetString("activitiesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Activities of the company.
        /// </summary>
        public static string companyActivitiesType {
            get {
                return ResourceManager.GetString("companyActivitiesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Experience.
        /// </summary>
        public static string exp {
            get {
                return ResourceManager.GetString("exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IT specialist.
        /// </summary>
        public static string it {
            get {
                return ResourceManager.GetString("it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Programmer.
        /// </summary>
        public static string programer {
            get {
                return ResourceManager.GetString("programer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Team.
        /// </summary>
        public static string team {
            get {
                return ResourceManager.GetString("team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Technology stack.
        /// </summary>
        public static string technology {
            get {
                return ResourceManager.GetString("technology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create and support enterprise platforms with .NET .NET Core..
        /// </summary>
        public static string work1ActivitiesType {
            get {
                return ResourceManager.GetString("work1ActivitiesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на “eCall” office/ product/ Ukraine, Kyiv | February 2018 – May 2022.
        /// </summary>
        public static string work1Company {
            get {
                return ResourceManager.GetString("work1Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Outsourced call center.
        /// </summary>
        public static string work1CompanyActivitiesType {
            get {
                return ResourceManager.GetString("work1CompanyActivitiesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3 dev/2 admin.
        /// </summary>
        public static string work1Team {
            get {
                return ResourceManager.GetString("work1Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на building enterprise platforms with .NET and Azure.
        /// </summary>
        public static string work2ActivitiesType {
            get {
                return ResourceManager.GetString("work2ActivitiesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на “DevRain”, remote / service / Ukraine, Kyiv | May 2022  – October 2022.
        /// </summary>
        public static string work2Company {
            get {
                return ResourceManager.GetString("work2Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Service company.
        /// </summary>
        public static string work2CompanyActivitiesType {
            get {
                return ResourceManager.GetString("work2CompanyActivitiesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на dev / QA / PM / TL / BA.
        /// </summary>
        public static string work2Team {
            get {
                return ResourceManager.GetString("work2Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на support enterprise platforms.
        /// </summary>
        public static string work3ActivitiesType {
            get {
                return ResourceManager.GetString("work3ActivitiesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на “Quipu” remote / product / Ukraine, Kyiv | August 2023  –2024.
        /// </summary>
        public static string work3Company {
            get {
                return ResourceManager.GetString("work3Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bank service company.
        /// </summary>
        public static string work3CompanyActivitiesType {
            get {
                return ResourceManager.GetString("work3CompanyActivitiesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на dev / QA / PM / TL / BA.
        /// </summary>
        public static string work3Team {
            get {
                return ResourceManager.GetString("work3Team", resourceCulture);
            }
        }
    }
}
